apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-oracle-pv-claim
  labels:
    app: db-oracle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-oracle
  template:
    metadata:
      labels:
        app: db-oracle
    spec:
      volumes:
      - name: db-init-volume
        configMap:
          name: db-init-cm
      - name: db-oracle-persistent-storage
        persistentVolumeClaim:
          claimName: db-oracle-pv-claim
      containers:
      - name: db-oracle
        image: gvenzl/oracle-xe
        env:
        - name: ORACLE_PASSWORD
          value: "mipassword"
        - name: APP_USER
          value: "appuser"
        - name: APP_USER_PASSWORD
          value: "mipasswordapp"
        resources:
          limits:
            memory: "3000Mi"
            cpu: "500m"
        ports:
        - containerPort: 1521
        volumeMounts:
        - name: db-init-volume
          mountPath: /container-entrypoint-initdb.d
        - name: db-oracle-persistent-storage
          mountPath: /opt/oracle/oradata
---
apiVersion: v1
kind: Service
metadata:
  name: service-oracle
spec:
  type: ClusterIP
  selector:
    app: db-oracle
  ports:
  - port: 1521
    targetPort: 1521
